name: Publish plumb5
on:
  push:
    branches:
      - main
      
  #schedule: ## Schedule the job to run at 12.am daily.
    #- cron: '45 19 * * *'
jobs:
  upload_files:
    runs-on: ubuntu-latest      
   
    name: Plumb5 Publish.
    steps:      
    
    - name: Checkout
      uses: actions/checkout@v2.3.4
     
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
     
    - name: Build solution
      run: dotnet build -c Release --verbosity minimal
