name: Publish plumb5
on:
  push:
    branches:
      - main

jobs:
  upload_files:
    runs-on: ubuntu-latest        
      
    steps:    
    - name: Checkout
      uses: actions/checkout@v2.3.4
     
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
     
    - name: Build solution
      run: dotnet build -c Release --verbosity minimal /home/runner/work/core/core/Plumb5MainCoreBuild/Plumb5MainBuild/WebApplication1/WebApplication1.csproj
