name: Publish plumb5
on:
  push:
    branches:
      - master
      
  #schedule: ## Schedule the job to run at 12.am daily.
    #- cron: '45 19 * * *'
jobs:
  upload_files:
    runs-on: ubuntu-latest      
   
    name: Plumb5 Publish.
    steps:      
    
    - name: Checkout
      uses: actions/checkout@v2.3.4
     
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
     
    - name: Build solution
      run: dotnet build -c Release --verbosity minimal /home/runner/work/Plumb5MainCoreBuild/Plumb5MainBuild/WebApplication1.csproj
     
    - name: Run tests
      run: dotnet test -c Release --verbosity minimal --no-build --no-restore /home/runner/work/Plumb5MainCoreBuild/Plumb5MainBuild/WebApplication1.csproj
   
    - name: Publish
      run: dotnet publish -c Release --no-build --no-restore /home/runner/work/Plumb5MainCoreBuild/Plumb5MainBuild/WebApplication1.csproj
